# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('web_interface_url', models.TextField(blank=True, max_length=500)),
                ('image_url', models.TextField(blank=True, max_length=500)),
                ('preview_url', models.TextField(blank=True, max_length=500)),
                ('video_url', models.TextField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('collection_id', models.IntegerField()),
                ('capture_start', models.DateTimeField()),
                ('capture_end', models.DateTimeField()),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CaptureCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('camera_id', models.IntegerField()),
                ('camera_alias', models.CharField(blank=True, max_length=30)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapsecore.Capture')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CaptureSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('capture_interval', models.IntegerField()),
                ('capture_days', models.CharField(max_length=15,
                                                  validators=[b'[', b'v', b'a', b'l', b'i', b'd', b'a', b't', b'e',
                                                              b'_', b'c', b'o', b'm', b'm', b'a', b'_', b's', b'e',
                                                              b'p', b'a', b'r', b'a', b't', b'e', b'd', b'_', b'i',
                                                              b'n', b't', b'e', b'g', b'e', b'r', b'_', b'l', b'i',
                                                              b's', b't', b']'])),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapsecore.Capture')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
