# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapsecore', '0002_auto_20170501_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='last_capture',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='capturecamera',
            name='camera_id',
            field=models.IntegerField(),
        ),
    ]
